# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Secretgenerator < Formula
  desc "Auditable random password generator for AI agents"
  homepage "https://github.com/rafaelperoco/secretgenerator"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rafaelperoco/secretgenerator/releases/download/v2.0.0/secretgenerator_2.0.0_darwin_amd64.tar.gz"
      sha256 "0d30bbdb34d4af850e8f517a4689833a4e1f6e7298e2775d1d20a996c06d5340"

      define_method(:install) do
        bin.install "secretgenerator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rafaelperoco/secretgenerator/releases/download/v2.0.0/secretgenerator_2.0.0_darwin_arm64.tar.gz"
      sha256 "c0097198d8b9828353d53139b376cb7cb61c2a897d81d977c1a4fbac8be50aab"

      define_method(:install) do
        bin.install "secretgenerator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rafaelperoco/secretgenerator/releases/download/v2.0.0/secretgenerator_2.0.0_linux_amd64.tar.gz"
      sha256 "37ce4b7cf028df517db825c45284e119330227667da53a3bff200c2299a97085"
      define_method(:install) do
        bin.install "secretgenerator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rafaelperoco/secretgenerator/releases/download/v2.0.0/secretgenerator_2.0.0_linux_arm64.tar.gz"
      sha256 "d4818a356b15c3263686762f82852ae592954211a8120d3b2f3209dfe615fba5"
      define_method(:install) do
        bin.install "secretgenerator"
      end
    end
  end

  test do
    system "#{bin}/secretgenerator", "--require-schema-version=1", "--json"
  end
end
